### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [codecentric/gopass-ui#103]
The project is great, but releases are quite rare – is there any chance to at least merge the dependency updates?

**Comment by ruettenm** [comment]
Hi @tomaszkrzyzanowski,

today I'll have a look. Thanks for the reminder :-)

**Comment by tomaszkrzyzanowski** [comment]
@ruettenm Thank you for merge, as I see the build passed.

One more thing – could you make a new release? Because the last one is from 2021 and all the changes merged since then are not in the release binary

Definitely, I could build this on my machine for my own purposes, but I think it might be good to the project to release refreshed binaries :)

**Comment by ruettenm** [comment]
I had a deeper look and there are so many dependencies which need updates. I tried to update them and get the project on my MBP with M1 Max running - without success 🙈

I decided to go for a completely new implementation based on tauri. I already have a good progress but still need a few weeks for the first release.

**Comment by tomaszkrzyzanowski** [comment]
Oh I see, I was thinking about introduce it in org where I work, so working build for M1 would be much appreciated 😃 

If you'd need someone for tests on Windows and Linux setups, feel free to ping

Also I can help with GH Actions builds if needed - I'm a DevOps and I don't know how to write nodejs code but I know a little about CI/CD :)

**Comment by ruettenm** [comment]
Nice to hear 🙂

In our team we are using gopass ui as tool to have a quick access to our password store to read/copy passwords. For maintaining and inserting we are very often using the terminal cli.

So my plan is to first focus on this features and later (if user are asking for more than this) implement update/insert secrets.

Would this be fine for you?

**Comment by tomaszkrzyzanowski** [comment]
That would be a great start :)

In my case, I'd like to simplify the process of accessing credentials for development team and later for business related teams (especially during onboarding phase)

Adding passwords is something which I can document and eventually replace later with gopass-ui.

I'm using the gopass right now for automation to secure the Terraform credentials, and I'm fine with using CLI but I'd like to implement gopass for other teams :)
