### ISSUE TITLE
tree not updated

### ISSUE THREAD

**Issue by jschmi** [codecentric/gopass-ui#24]
Ubuntu 18.04, all updates installed
gopass configured and working on command line, environment test of gopass-ui says "Everything looks fine"
using local password store
* When adding a password using the + button, it is not displayed in the left tree
* When deleting a password, it is not removed from the left tree. When clicking on it then, the following is displayed: 
1.Loading, please wait
2.Still doing something...
3.It seems to takes some time... (should be "take", not "takes")
4.Doop di doop di douuu
5.I'm sorry that it takes longer
6.Maybe there is a persistent problem. Sorry for that!

Workaround is to restart the gui every time a password was added or deleted, then the updated tree is displayed correctly

**Comment by ruettenm** [comment]
Hi, thanks again for your feedback.

In our current project we are using gopass only as a shared password store. But I'll try to reproduce and fix your issue.

**Comment by jverhoelen** [comment]
Thanks for reporting @jschmi, I'm working on it currently.

**Comment by jverhoelen** [comment]
PR #35 was merged into master. Next release will include an improved version of the tree.
