### ISSUE TITLE
Debian 9.9 (stretch)

### ISSUE THREAD

**Issue by jschmi** [codecentric/gopass-ui#25]
gopass is configured and working on commandline. After installing following the instructions, gopass-ui doesn't start:

gopass-ui 
[2682:0710/084341.870175:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Gopass UI/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

When setting the mode with:

chmod 4755 /opt/Gopass UI/chrome-sandbox

it still doesn't start:
gopass-ui 
Trace/breakpoint trap

**Comment by ruettenm** [comment]
Thanks for your feedback. Until now we are mainly developing and testing on mac osx. I'll try to reproduce and analyze your issue on Friday anyhow.

**Comment by ruettenm** [comment]
Hi @jschmi sorry but we are not able to reproduce the issue.

I added the following notice to the README to make sure that we are only testing the macOS releases ;-)
`We'll only test the MacOS builds and are not able to support you with linux and windows releases. We are welcome to receive pull requests to tackle linux and windows issues.`

We are happy to see a pull request for this :-)

If you are interested you can find our development docs here:
https://github.com/codecentric/gopass-ui/blob/master/docs/development.md
