### ISSUE TITLE
How to sync the secrets from the Gopass UI 

### ISSUE THREAD

**Issue by JhansiLakkaraju1848** [codecentric/gopass-ui#26]
So we have deployed our gopass repository to github. I tried using the Gopass UI and updated the store. But couldn't sync it with github.

**Comment by jverhoelen** [comment]
Hey @JhansiLakkaraju1848 
Gopass UI does not yet have a feature to add/init/checkout new password stores for your local gopass. It only provides functionality after having a minimum of one password store available to use. Sorry. Currently we do not have a roadmap for new features but are starting to investigate reported bugs and errors.

If this does not answer your issue, please explain a little bit further.

**Comment by jverhoelen** [comment]
For the time being and the sake of better overview, I will close this issue. However, the idea of adding stores via the UI will be added to our backlog.
