### ISSUE TITLE
Arch Linux Release Package

### ISSUE THREAD

**Issue by stevenklar** [codecentric/gopass-ui#27]
Hi, I use arch btw.

Like this project a lot and converted the .deb package with debtap to a pacman (arch linux package manager) compatible tar.gz file.

Would be awesome to have such a package also released for fellow arch linux users which loves gopass and also want to use your gopass-ui right away.

I don't know about the process to get into the AUR (arch user repository) - but providing a package here in github is good enough.

Thank you
Steven

**Comment by ruettenm** [comment]
Hi @stevenklar, sorry for the late reply. 

I tried to build a "pacman" release. Could you please have a look if this would work for you? Because I'm not able to test it on my mac ;-)

https://drive.google.com/file/d/1MJav8SAN73AQY2Cu3LuIEQEtT67g1a_f/view?usp=sharing

Thanks in advance

**Comment by stevenklar** [comment]
Hi @ruettenm 

Converting the deb package by hand worked for me. This package does not place the binary anywhere.

```~/Downloads at ☸️  production-master1 (booking-api-feature-pipeline)
➜ sudo pacman -U gopass-ui-0.5.0.pacman
Lade Pakete...
Warnung: gopass-ui-0.5.0-1 ist aktuell -- Reinstalliere
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

Pakete (1) gopass-ui-0.5.0-1

Gesamtgröße der installierten Pakete:  275,68 MiB
Größendifferenz der Aktualisierung:    0,00 MiB

:: Installation fortsetzen? [J/n]
(1/1) Prüfe Schlüssel im Schlüsselring                          [###################################] 100%
(1/1) Überprüfe Paket-Integrität                                [###################################] 100%
(1/1) Lade Paket-Dateien                                        [###################################] 100%
(1/1) Prüfe auf Dateikonflikte                                  [###################################] 100%
(1/1) Überprüfe verfügbaren Festplattenspeicher                 [###################################] 100%
Warnung: konnte Dateiinformationen für usr/opt/ nicht ermitteln
Warnung: konnte Dateiinformationen für usr/opt/.PKGINFO nicht ermitteln
:: Verarbeite Paketänderungen...
(1/1) Installiere gopass-ui                                     [###################################] 100%
Warnung: Datei nicht in Dateiliste des Pakets gopass-ui gefunden. Überspringe Entpacken von opt/
:: Starte post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating icon theme caches...
(3/3) Updating the desktop file MIME type cache...

~/Downloads at ☸️  production-master1 (booking-api-feature-pipeline) took 10s
➜ gopass-ui
zsh: command not found: gopass-ui
```

If you know how to use docker, there is an official "archlinux/base" image which can be used for testing.

Thank you for the effort!

**Comment by jverhoelen** [comment]
Hi @stevenklar,
with [0.7.0](https://github.com/codecentric/gopass-ui/releases/tag/v0.7.0) being released few minutes ago I also added a `.pacman` file that has been built directly by electron-builder.

Could you test if it solves your problem? I hereby added pacman to the list of packages that we generate for each release.
