### ISSUE TITLE
Unable to display and edit multiline content 

### ISSUE THREAD

**Issue by fw8** [codecentric/gopass-ui#28]
With QtPass it is possible to edit/retrieve multiline content. This does not seem to be possible with the current version of Gopass UI (0.4.0). It would be nice to have this feature also in the Gopass UI!

**Comment by ruettenm** [comment]
Hi @fw8 

we are currently not implementing new feature into gopass ui but we are happy to see a pull request for this :-)

If you are interested you can find our development docs here:
https://github.com/codecentric/gopass-ui/blob/master/docs/development.md

**Comment by jverhoelen** [comment]
Multiline secret handling was now implemented and merged into master (#33). It will be included in the next release which will be published within the next days or weeks.
