### ISSUE TITLE
cannot see / edit passwords when safecontent is set to true on gopass

### ISSUE THREAD

**Issue by CircleCode** [codecentric/gopass-ui#30]
when `safecontent` is enabled, the password shown is `No safe content to display, you can force display with show -f.Copying password instead.✔ Copied XXX to clipboard. Will clear in 45 seconds.` and the edit button shows the exact same text.

**Comment by ruettenm** [comment]
Thanks for reporting the bug. I'll try to reproduce and fix it.

**Comment by ruettenm** [comment]
I was able to reproduce the issue. This will be fixed in the next release.
