### ISSUE TITLE
Accessing the Explorer generate a JS error in Mojave

### ISSUE THREAD

**Issue by ScrumpyJack** [codecentric/gopass-ui#31]
Start Gopass UI
Close Explorer window
Start Explorer window from the Gopass UI toolbar and you get.

```
Uncaught Exception:
Error: Object has been destroyed
    at click (/Applications/Gopass UI.app/Contents/Resources/app.asar/dist/main.js:42:3322)
    at MenuItem.click (/Applications/Gopass UI.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/Applications/Gopass UI.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)
```

In addition, search window will allow searching, but clicking on a password path does nothing.

**Comment by jverhoelen** [comment]
Hey @ScrumpyJack 
Thanks for your report. Sorry for the late reply and bad experience with the tool. I'll try to investigate. One question: did Gopass UI work for you before upgrading to Mojave? This would help me understanding it. I'm not on Mojave myself, yet, but in the process of upgrading for myself I will then be able to troubleshoot it. Thanks in advance for your answer

**Comment by ScrumpyJack** [comment]
Actually this is my first install of gopass-ui. I've not tested it on other that Mojave (and I don't have anything other than Mojave to test it on)

Hey and stop being so nice, it's disconcerting ;)

**Comment by jverhoelen** [comment]
Reproduced and fixed on master. The fix will be part of the next release.

**Comment by ScrumpyJack** [comment]
Awesome. Will test this.
