### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ScrumpyJack** [codecentric/gopass-ui#38]
Thanks for 0.60, it's fixed the issue #31 in Mojave and Catalina.

The following feature would be great though:

In the explorer, have the passwords hidden by default, with one extra button like this:

[COPY TO CLIPBOARD] [SHOW] [EDIT] [DELETE]

On OSX, the trend in menu bar icons is monochrome. Can we get a menu bar icon to match the dark or light themes of OSX?

<img width="992" alt="gpui" src="https://user-images.githubusercontent.com/3187469/72801567-aa8b0600-3c41-11ea-905e-422bcdcf6915.png">

**Comment by jverhoelen** [comment]
Hey again @ScrumpyJack, cool to receive feature requests from your side.
* Auto hide for secret values sounds good for me. I guess we would make this option configureable through settings (@ruettenm, what do you think?).
* Different tray icons for normal and dark mode should be possible. I think @ruettenm already did this for another Electron project he maintains.

**Comment by ruettenm** [comment]
I created an issue and already MR for the **tray topic**:
https://github.com/codecentric/gopass-ui/issues/39 

For the hide secret value topic I created this issue:
https://github.com/codecentric/gopass-ui/issues/41
