### ISSUE TITLE
Settings: Make "global search window" shortcut configurable

### ISSUE THREAD

**Issue by jverhoelen** [codecentric/gopass-ui#4]
The shortcut to open the global search window is `cmd + shift + p`. It should be configurable. The setting should be persistent.

**Comment by ruettenm** [comment]
**This should be configurable:**
* SHORTCURT for Global Search Window
* LIGHT and DARK theme
* start On Login
* show Tray
* hide explorer when Global Search Window is closed

**Comment by sheldonhull** [comment]
I'll add that I just searched for this as the current mapping conflicts with all text editors like Vscode and sublime that use the control pallet.

**Comment by ruettenm** [comment]
Thats nice. Thanks! Did you already had the time to play around with the settings @sheldonhull? Otherwise I would continue with this in the next days.

**Comment by jverhoelen** [comment]
As of the latest commit on master, the global search window shortcut as well as the character length of generated secret values is now configurable on the settings page.

The shortcut configuration does also feature validation which adheres to the Electron docs: https://www.electronjs.org/docs/api/accelerator#available-modifiers - as Gopass UI targets mostly tech-oriented people, enforcing usage of this notation should be fine I guess.
