### ISSUE TITLE
hide secret values in explorer

### ISSUE THREAD

**Issue by ruettenm** [codecentric/gopass-ui#41]
Add a configuration to automatically hide the secret values in the explorer.

In this mode the user has to click a "show" button next to the "copy to clipboard" button to show the value of the secret.

![image](https://user-images.githubusercontent.com/2926623/72943340-1ff7f300-3d76-11ea-9a65-9b1fe0efab62.png)

**Comment by ScrumpyJack** [comment]
This is awesome, and makes sense, considering you can copy-to-clipboard with `gopass -c` and not worry about showing secrets.

**Comment by jverhoelen** [comment]
Implemented this [in the latest commit on master](https://github.com/codecentric/gopass-ui/commit/145d0736fc2fe9ca955c6c016b94554e6de6a897). It will go into the next release 😉
