### ISSUE TITLE
Feature request: Hide the app from the Finder in OSX

### ISSUE THREAD

**Issue by ScrumpyJack** [codecentric/gopass-ui#43]
As this is an application that I launch at boot and is running constantly in the background, it would be nice to be able to remove it from the Dock in OSX when it is running, as we can access from the Task Bar icon. All the gopass-ui settings are accessed through the UI.

This would further streamline this excellent tool.

**Comment by jverhoelen** [comment]
@ruettenm let's discuss whether we agree with that soon ;-)

**Comment by ruettenm** [comment]
I already build such a feature for an other electron app. I can try to take care this Friday ;-)

**Comment by ruettenm** [comment]
Hey @ScrumpyJack, 

I found some time to have a deeper look into your request and tested the application without a dock entry. The bad thing I found out is: When the app is not in the dock you are not able to switch to the app via mac "app switch". So you always have to click on the tray to open the explorer again.

So the usecase
1. open gopass ui
2. copy username
3. switch to your application and insert the username
4. **switch back to gopass ui**
5. copy password
3. switch to your application and insert the password

would not work. 

Would you still like this feature?

**Comment by ScrumpyJack** [comment]
by tray, i assume you mean the Task Bar, so yes, that's the idea, to hide the app from the switcher and the Dock, and access it through it's lovely new monochrome task bar icon :)

**Comment by jverhoelen** [comment]
Hey @ScrumpyJack,
@ruettenm and me just discussed if we would like to adopt this behaviour.

We would not find this change beneficial to the user experience. From our experience, a lot of people are working with the app switcher on MacOS and like to keep commonly used applications in their Dock to use it actively. So are we 😃
Therefor, I hope the tool stays handy for you although we're denying the request.

Best,
Jonas

**Comment by ScrumpyJack** [comment]
Thanks for the 0.70 update! awesome work.

Bummer about the app switcher hiding thing.
Can you make it an option so those that want to hide that app can hide it?
I use Command-Shift-P when I need to search for a password, not the app switcher, I like to keep the app-switcher with the fewest amount of apps possible. 

Regarding the dock, I don't keep the app in the dock as i have set it to start up when i log in :)
