### ISSUE TITLE
Editing bug

### ISSUE THREAD

**Issue by danielKugler** [codecentric/gopass-ui#48]
BUG:
By clicking on "EDIT" Button - then click on any other entry in the stores tree = the input stays in edit mode with the information of the last active entry but shows the new clicked entrys name. This is confusing and leads to input mistakes from a ux perspective.

EXPECTED BEHAVIOUR:
Modal which askes if i want to cancel the operation or to save it on leaving this view.
OR
If there have been no changes simple quit the edit mode.

Thanks in advance.

**Comment by jverhoelen** [comment]
Hey @danielKugler,
thanks for reporting this. This bug also applies to the secret deletion functionality in a similar way.

I fixed both of them in the [latest commit on master ](https://github.com/codecentric/gopass-ui/commit/1c93f60a45e6c4047209d56b23ee1e80e897c6ae). It will be part of the next release.
