### ISSUE TITLE
File access fails because of special chars in file or filename

### ISSUE THREAD

**Issue by promasu** [codecentric/gopass-ui#49]
When having Chars like "(", ")" or Backtick inside the file or password gopass-ui is not able to save or access the file because of sh errors as those Chars are not escaped and are valid sh syntax.

**Comment by jverhoelen** [comment]
Hey @promasu,
thanks for reporting this. I addressed this kind of bug for "Gopass bridge"-related behaviour in [my latest commit on master](https://github.com/codecentric/gopass-ui/commit/a2bf42ed0a21498698992ee41473f65e27a6eb6b). Also used the opportunity to establish some basic test coverage for this part of the project.
The fix will be part of the next release.

**Comment by promasu** [comment]
Thanks a lot!
