### ISSUE TITLE
package for arch linux should be published to aur repository and problem installing the dependencies

### ISSUE THREAD

**Issue by dummys** [codecentric/gopass-ui#69]
Hi,
The package should be publsihed in the aur repo: https://aur.archlinux.org/ rather than compiling some pacman magic package.
I get lof of trouble when I want to install your package:

```bash
loading packages...
resolving dependencies...
warning: cannot resolve "libappindicator-sharp", a dependency of "gopass-ui"
:: The following package cannot be upgraded due to unresolvable dependencies:
      gopass-ui
:: Do you want to skip the above package for this upgrade? [y/N] 
```
Then I tried to install `libappindicator-sharp` from aur but it is a nightmare too:

First I get problem with GPG keys, which was solved using: `gpg --keyserver pool.sks-keyservers.net --search-keys "charles.kerr"` and choosing your second key.
Then I get this inside the `makepkg -sri` command: 

```bash
  -> Creating working copy of libappindicator bzr repo...
brz: ERROR: Not a branch: "/home/mofo/build/yay/libappindicator-sharp/libappindicator/.bzr/branch/".
==> ERROR: Failure while creating working copy of libappindicator bzr repo
    Aborting...
checking dependencies...
```

I get latest version of Arch linux, upgraded of today.

I get lot of trouble installing the gopass-ui package for Arch linux. When I tried to

**Comment by Ozon2** [comment]
Hi, I published the package on AUR, could you try installing it @dummys ? https://aur.archlinux.org/packages/gopass-ui-bin/

**Comment by dummys** [comment]
so far so good. I installed it without any problem. Great works !
