### ISSUE TITLE
feature: add auto completion when creating new secret

### ISSUE THREAD

**Issue by dummys** [codecentric/gopass-ui#71]
Hi, is it possible to add auto completion when creating new secret for the path ?

and also is it possible to add a "right click" on a folder to add a new secret and the path will be already filled with the pass of the folder ?

**Comment by ruettenm** [comment]
Hi, thanks for the ideas. Currently we don't have so much time to work on this side project.

If you want to see this feature on short term: Feel free to open a pull request ;-)

**Comment by ruettenm** [comment]
duplicate #61
