### ISSUE TITLE
Can not see the secrets/stores when I use gopass clone

### ISSUE THREAD

**Issue by dawidek88** [codecentric/gopass-ui#73]
gopass-ui: v0.7.0 

My problem is that I can only see my locally generated secrets/stores in the user interface.
It is actually not possible to see the secrets when I using gopass clone.

Do any of you guys have the same UI problem?

**Comment by ruettenm** [comment]
Hi, thanks for reporting the issue.

Which gopass version are you using? We are using the command `gopass list --flat` to find all secrets. Which secrets do you see when you execute it in your terminal.

best regards
Matthias

**Comment by dawidek88** [comment]
Hello Matthias,

it works with gopass version 1.9.2. I think I have a problem with my VM (3D graphics driver) and the gopass-ui. Thanks for your help. I'll check if it works on my normal PC.

Best regards
David

**Comment by dawidek88** [comment]
It was a problem with my vm.
