### ISSUE TITLE
Can not copy passwords to the clipboard

### ISSUE THREAD

**Issue by bidzoni** [codecentric/gopass-ui#74]
I can not copy a password to the clipboard on macOS Big Sur. 
When I try to do it I receive the "Oops, something went wrong. Please try again" message. 
gopass-ui was installed via brew cask, version 0.7.0

**Comment by TheFrozenDuck** [comment]
The same thing happens on a Linux distro. I installed it via AUR (0.7.0) using the "official" installer.

**Comment by isodude** [comment]
Please refer to #77
I compiled and checked locally and it works properly now.

**Comment by ruettenm** [comment]
Thanks for the MR. gopass changed the CLI command structure within the latest versions.

**Comment by ruettenm** [comment]
The fix will be part of the next release.

**Comment by lockejan** [comment]
Still occuring on my site. Is this related or a new bug?

- gopass:1.12.7
- gpg 2.3.1
- git 2.32.0
- gopass-ui: 0.7.0
- macos bigSur: 11.4
